spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: test
  mvc:
      static-path-pattern: /**
  servlet:
    multipart:
      enabled: false
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8080
  address: localhost
maxPostSize: 102400000
#context:
#  listener:
#    classes: com.heeexy.example.event.InitDataListener

# ICE配置文件名称
ice:
  config:
    file: config-dev.client
# 产线IP配置文件
aginglines:
  json:
    file: aginglines-dev.json