spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: test
  mvc:
      static-path-pattern: /**
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8080
  address: localhost
context:
  listener:
    classes: com.heeexy.example.event.InitData